### ISSUE TITLE
Not Equals operator not working

### ISSUE THREAD

**Issue by famda** [hector-co/QueryX#11]
Hello,
I'm having a strange behaviour (possibly a bug?)

I'm trying to execute a query using a not equals operator:
/roles?filter=id!='some id'

and I'm having this exception:

![image](https://github.com/hector-co/QueryX/assets/26621392/144f077a-aec1-4db4-9f88-b872dc9b46d1)

I also tried the Not operator, since the equals is working. But the exception is the same.

Can you help? 
Thanks in advance.

**Comment by hector-co** [comment]
It is not implemented 😱. It seems I missed that operator when refactoring for version 2.
I am adding the operator and will prepare a new release. Thanks for your comments!

**Comment by famda** [comment]
No worries, i noticed that the operator was missing on the source code.

I'm glad I was able to help!

Keep up the good work!
