### ISSUE TITLE
Question on new config system release v2

### ISSUE THREAD

**Issue by famda** [hector-co/QueryX#7]
Hello,
I'm testing the new v2 releases and I identified something that I don't know how to solve.

![image](https://github.com/hector-co/QueryX/assets/26621392/2c78a75a-ed92-4692-9f1f-ab91ac8c55b0)

On my database model I have an instance of UserRole that includes the User and the Role and on, my api model, I don't have it.
Basically there is one depth level less on the mapping ApplicationAccess -> Access

What is the best option to solve this? (maybe you will solve it on the config or should I use it as custom query?)

Thanks in advance ;)

**Comment by hector-co** [comment]
Hi, nested property mapping is not currently supported, this is one of the features I have on my to-do list. The only solution I can think of is to use a custom filter as you mention.

I will create a ticket to handle this scenario, initially I was thinking of adding this in a 2.1 release, but I think I can dedicate some time to it these days.

**Comment by famda** [comment]
Awesome!! 
The properties Region, Country and Resource are aldo nested (e.g Country.Name) and those are working perfectly, but I see your point (sub-nested are not).
Meanwhile, I'll try to adapt a custom property mapping to it.

Thanks a bunch!!

**Comment by hector-co** [comment]
I am closing this issue as this behavior will be addressed in #8
